FROM continuumio/miniconda3

WORKDIR /data
WORKDIR /code

# python version
RUN conda update -y conda
RUN conda install -y python=3.11
RUN conda install -y conda-forge::gxx conda-forge::gcc
# RUN conda install -y conda-forge::gxx=12.2 conda-forge::gcc=12.2
RUN conda install -y conda-forge::tesseract

RUN conda install -y --solver=classic --force-reinstall \
    conda-forge::conda-libmamba-solver conda-forge::libmamba \
    conda-forge::libmambapy conda-forge::libarchive
RUN conda install -y conda-forge::libpython-static conda-forge::patchelf conda-forge::binutils
# RUN conda install -y conda-forge::clang

RUN conda install -y conda-forge::nuitka
# RUN python -m pip install pytesseract