FROM continuumio/miniconda3

WORKDIR /data
WORKDIR /code

# python version
RUN conda update -y conda
RUN conda create -y -n py311 python=3.11 \
    conda-forge::gxx conda-forge::gcc
# RUN conda install -y --solver=classic --force-reinstall \
#     conda-forge::conda-libmamba-solver conda-forge::libmamba \
#     conda-forge::libmambapy conda-forge::libarchive

RUN echo "source activate myenv" > ~/.bashrc

# install tesseract
# RUN conda install -y conda-forge::libpython-static conda-forge::patchelf
# RUN conda install -y conda-forge::tesseract

# install dependencies
# RUN python -m pip install nuitka
# RUN python -m pip install pytesseract
