FROM continuumio/miniconda3

WORKDIR /code

RUN conda create -y -n venv python=3.12
RUN conda install -y conda-forge::autopep8 conda-forge::conda-build \
    conda-forge::isort conda-forge::pip

COPY ./requirements.txt /code/requirements.txt

RUN /bin/bash -c " source activate venv \
    && python -m pip install -r /code/requirements.txt"
