http_options: 
  host: 0.0.0.0
  port: 8000
  request_timeout_s: 600
  keep_alive_timeout_s: 30

applications:
- name: default
  route_prefix: /v1
  import_path: src.runapp:music_generator
  runtime_env: {}
  deployments:
  - name: MusicGenerator
    num_replicas: 1